---
title: "CrispDM_analysis_report"
author: "Pranav Sunil Raja"
date: "2024-11-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

## Introduction

The objective of this project is to identify the key determinants of student success in the Massive Open Online Course (MOOC) titled “Cyber Security: Safety At Home, Online, and in Life,” offered by Newcastle University through the FutureLearn platform. This study leverages raw data collected from seven different runs of the course, utilizing learning analytics techniques to uncover effective measures of student engagement. My analysis and findings will benefit Newcastle University’s course instructors and individuals running similar online courses, as they seek to enhance student engagement rates and improve student performance. Employing the CRISP-DM framework, this report presents the results of two iterative cycles of data mining, which will serve as a valuable resource for improving the course’s effectiveness and promoting it in a manner that aligns with the needs of the target audience.

## Round 1 

### 1. Business Understanding 
This report is based on an inquiry into a Future Learn-hosted online course. Future Learn is an online learning platform that has worked with a number of world-renowned universities and organisations to provide a diverse set of courses. One of them is Newcastle University’s Cyber Security, for which we will conduct a forensic examination in the form of a data analysis in this report. Overall this analysis might be beneficial to someone who is running the course or the course creator.

### 1.1 Background
Learning Analytics, a key facet of Data Science, involves the systematic measurement, analysis, and reporting of learner data to enhance educational out comes. Future Learn which is an educational website, they are primarily interested in anything that would improve and provide some actionable insights for informed decision-making, intervention strategies, and ongoing course refinement. We hope to use this method to assess the course’s progress and determine where the course is prospering and where it is not. After we’ve addressed these difficulties, we’ll be able to devise a strategy for improving the course as needed. 

### 1.2 Business Objective
By employing the CRISP-DM methodology, this initiative unifies diverse data sources—ranging from on-campus facility usage to VLE interactions. The primary objective of this learning analytics project is to leverage data science methodologies for the FutureLearn MOOC Cybersecurity course. The goal is to measure, collect, analyze, and report data about learners and their contexts. Because Future Learn is an educational website, they are primarily interested in anything that would improve the learning experience, increase student interaction, and encourage students to enroll in more online courses. We hope to use this method to assess the course’s progress and determine where the course is prospering and where it is not. After we’ve addressed these difficulties, we’ll be able to devise a strategy for improving the course as needed.

### 1.3 Success Criteria 
The success of this learning analytics initiative lies in the precise and accurate utilization of data science methodologies to enhance the FutureLearn MOOC Cybersecurity course. The results should be not only 1 relevant to stakeholders but also easily accessible and interpretable, fostering informed decision-making. The success criteria encompass ensuring data accuracy, relevance to stakeholders, accessibility and interpretability of results, applicability to learning enhancement, and the ability to inform strategic decisions for optimizing the online learning environment. Ultimately, success will be measured by the project’s capacity to deliver actionable insights that contribute to the continuous improvement of the course and positively impact the learning experience.

### 1.4 Research Question
### “Factors influencing completion, purchase and attrition of online course”

### 1.5 Inventory of Resources
Dataset: Data is made available from 7 runs of a massive open online course (MOOC) entitled “Cyber Security: Safety At Home, Online, and in Life”. The 7 sets of raw data contains information on learners as they progressed through the course and some details on their profile.
Course Overview: The seven course overview files describe course content and content type of each run.

### 1.7 Data Mining 
 The goal is to identify hidden patterns or trends within the data that are not immediately apparent. The detailed examination aims to uncover results to improve their marketing strategies, focus upon reducing the attrition rate and improve the purchase rates and overall resulting in the cost effectiveness and profit margin.  By leveraging data-driven insights, the course analytics not only enhance the overall learning experience for students but also empower course designers and instructors to refine content, assessments, and interventions. The success is defined by the ability to unearth actionable knowledge and insights that can be translated into meaningful business strategies, improvements, or innovations.
 
### 1.8 Initial Assessment of tools and techniques
1. Git:  
Strengths: Git is an excellent version control system that enables collaboration, tracks changes, and provides a centralized repository for code and documentation.  
Opportunities: Ensure consistent and descriptive commit messages.  

2. Project Template in R:  
Strengths: Utilizing a project template in R promotes organization, reproducibility, and efficient collaboration. It establishes a standardized structure for your project.  
Opportunities: Ensure that the project template aligns with best practices and is adaptable to changing project requirements.  

3. ggplot, Tidyverse, dplyr:  
Strengths: These R packages, especially ggplot and dplyr from the Tidyverse, offer powerful tools for data visualization and manipulation. They support a clean and efficient coding style.  
Opportunities: Stay updated with the latest versions, explore advanced features, and consider incorporating additional Tidyverse packages as needed.  

4. CRISP-DM (Cross-Industry Standard Process for Data Mining):  
Strengths: Following the CRISP-DM framework demonstrates a structured approach to data mining, ensuring that the project progresses through well-defined phases.  
Opportunities: Regularly review and adapt the CRISP-DM process to suit the evolving needs of the project. Emphasize clear communication and documentation.  

### 2. Data Understanding  

This phase encompasses the comprehensive documentation of data collection, description, and exploration. It involves providing information on the quality of the data, shedding light on its strengths, limitations, and overall reliability.

### 2.1 Data collection
Raw data is collected from the 7 course runs of a massive open online course (MOOC) entitled “Cyber Security: Safety At Home, Online, and in Life” made by Newcastle University. This data has information on characteristic information on every learner and steps of how they progressed through the course.

### 2.2 Data Files Description
For our cycle 1 analysis we only use enrollments.
Following Data files can be viewed in the course runs.   
1. Archetype Survey Response: This sheet contains the learner id's and their Archetypes.   
2. Enrollments: The file consists of profile information of every learner id along with the enrollment and un-enrollment time frame.  
3. Leaving Survey Response: This data sheet captures the leaving reasons and step activity of learners who unrolled from the course.  
4. Question Response: This sheet contains the performance data of each student with the quiz content by storing their responses and attempts to solve each question. 
5. Step Activity: This data sheet consists of the first visited and last completed time stamps of each activity that the learner's have visited.
6. Team Members: This file has details on the team members and their contribution to the course.  
7. Video Stats: Video stats data sheet has information on the video content of the course. It has details like video duration, total views, downloads, views by percentage and total viewers on each device or demographic. 
8. Weekly Sentiment Survey: The sheet captures comments and ratings of different learners for each week of the course.

### 2.3 Data Exploration
We want to understand different students profile who engage with the course. We're trying to find out if there are any patterns in the profiles across 7 runs. In my initial look at the data, there are some files that have information about students, but they don't help us with our main question. Some files, like Enrollments Data and Leaving Survey Response, have missing or unknown information. Also, not all files are available for every course run. For example, the archeotype survey responses and leaving survey response file is only there for the 4th, 5th, 6th and 7th runs of the course.

### 2.4 Data Quality
